### ISSUE TITLE
UART not working on E1

### ISSUE THREAD

**Issue by rystein** [makerbase-mks/MKS-GEN_L#2]
I'm having issues utilizing E1 for my Z2 stepper. I saw the previous issue with dual Z and added those pin details. Unfortunately M122 reports that Z2 is "All Low". I'm using TMC2208 V3 and the other 4 work as expected but the issue only occurs on E1. I've swapped the driver with another port and it was the same results so I've ruled out a bad driver. Thanks in advance.

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-GEN_L/issues/1
