### ISSUE TITLE
 establish UART communication with my Mac

### ISSUE THREAD

**Issue by kaine1973** [makerbase-mks/MKS-GEN_L#22]
Hello,

 I am currently facing an issue with configuring UART on my 3D printer running Marlin 2.0, and I am seeking some guidance.

I have searched through the official documentation, but unfortunately, I couldn't find specific information regarding the configuration of UART in Marlin 2.0. I have checked Configuration.h and Configuration_adv.h files, but there seems to be no direct settings like SERIAL_PORT, RX_PIN, or TX_PIN.

My goal is to establish UART communication with my Mac, and I would appreciate any help or guidance on how to configure UART settings in Marlin 2.0. If there have been changes or new methods introduced in the latest version, please point me in the right direction.

I have also checked the official GitHub repository, but the information there is quite extensive, and I may have overlooked something. If anyone has experience with configuring UART in Marlin 2.0 or can direct me to relevant resources, I would be grateful.

Thank you in advance for your assistance.

**Comment by sdoe0** [comment]
Hello kaine, in configuration.h @section machine, i got to choose the Board according to boards.h 
![image](https://github.com/makerbase-mks/MKS-GEN_L/assets/69821734/41bfc31d-3baa-420b-a97f-1411b8a3ffd8)

Then there are two serial ports to set. One for Host Connection and one for Stepperdriver 
![image](https://github.com/makerbase-mks/MKS-GEN_L/assets/69821734/b199b8be-c944-43bc-9579-6f8c326b4add)

This is for SGEN_LV2 but i think for gen_L its analog. 
In Marlin 2.0 the Pins are declared by selecting a Board-Type

**Comment by kaine1973** [comment]
> Type

Thank you, dMarabou. I am glad that you replied.

At the last time, I set SERIAL_PORT value 0 (default), and SERIAL_PORT_2 value to 1, It did not work.
<img width="544" alt="截屏2023-12-06 09 24 33" src="https://github.com/makerbase-mks/MKS-GEN_L/assets/32561008/49dac06a-243b-4d8c-9fe4-cd0b91d6870d">

Wiring like this, red to tx, and green to rx:
<img width="896" alt="截屏2023-12-06 09 30 43" src="https://github.com/makerbase-mks/MKS-GEN_L/assets/32561008/24c2825b-091a-4cbb-86af-776a5fe4a1ef">

And I did this because I read this: https://github.com/MarlinFirmware/Marlin/issues/10219#issuecomment-375999216

I'll try your configuration later, see if it works.

Thank you !

**Comment by kaine1973** [comment]
Sorry, changing value of SERIAL_PORT to -1 raises an error on building:
<img width="898" alt="截屏2023-12-06 10 20 58" src="https://github.com/makerbase-mks/MKS-GEN_L/assets/32561008/5cd920cb-1181-49f2-b460-ce847012583b">

**Comment by sdoe0** [comment]
Hi @kaine1973,
Are u trying to establish a direct Connection between the Mac and the Board via the AUX Connector? U should use the USB Port for that. Because Otherwise u have to change the Pin Numbering in the Boards.h-File 

Can u post a Photo of ur setup or describe it ?
