### ISSUE TITLE
Lack of jumper for Z+ on J13 

### ISSUE THREAD

**Issue by lonelymyp** [makerbase-mks/MKS-GEN_L#7]
To make sensorless parking on the Z axis, there is only a jumper to use Z_min on J13 MKS-GEN_L 2.1. 
But if this is a CoreXY printer, the bead is parked at the maximum height when Z_max is triggered.
I had to connect the necessary contacts with a jumper wire.

The rest of the axes have jumpers for both the minimum and maximum.

**Comment by makerbase-mks** [comment]
I think! You can define Z diag to Z max pin

**Comment by makerbase-mks** [comment]
@lonelymyp  Has this problem been solved?

**Comment by lonelymyp** [comment]
@makerbase-mks yes
