### ISSUE TITLE
Sensorless parking tmc2209 on Z does not work

### ISSUE THREAD

**Issue by lonelymyp** [makerbase-mks/MKS-GEN_L#8]
I have configured all 3 axes of the printer for sensorless homing for marlin 2.0 + gen_l 2.1
The parameters were adjusted strictly according to the video instructions, all 3 axes are identical.
The X and Y axes are parked without problems and the Z axis does not trigger. 
No signal appears on the contact Zdiag. It seems that the driver is simply not giving the desired signal. Changed the driver in places, did not help.

Maybe something else needs to be adjusted for the z axis?

**Comment by lonelymyp** [comment]
It looks like if the axle parking speed is higher than HYBRID_THRESHOLD for that axle then no parking signal is generated.
HYBRID_THRESHOLD must be higher than the parking speed for parking to work correctly.

**Comment by makerbase-mks** [comment]
So, sensorless homing is works?

**Comment by lonelymyp** [comment]
Yes, after setting HYBRID_THRESHOLD

**Comment by makerbase-mks** [comment]
I will close it
